### ISSUE TITLE
Reactive / Stream / Dataflow Abstractions

### ISSUE THREAD

**Issue by sirinath** [scylladb/seastar#108]
Since a future can only have one result it is possible to have a stream abstraction which has the ability to process multiple values. As new values are supplied to the Dataflow network computation propagate.

**Comment by avikivity** [comment]
Please use the mailing list for development discussions.

**Comment by nyh** [comment]
As Avi said, the bug tracker really isn't the best place for such a discussion, but since you already asked here, I'll bit.

When you consider a stream of values, invariably the issue of buffering comes into play: do we start working on producing the next value as soon as the previous value is consumed, or perhaps just when the consumer asks for the next value? Should we even start working ahead on more than one value and buffer it?

Our concept of seastar::pipe may be what you're looking for. A has one side writing data into it, and one side reading values, with a fixed-sized buffer. The reader waits when the pipe buffer has become empty, and the writer waits when it becomes full (e.g., enough values have been produced, and now we should wait for the reader to consume at least some of them).

If seastar::pipe is not good enough for your needs, I will be happy if you start a discussion on the mailing list of what you're looking for in a better stream abstraction.

**Comment by sirinath** [comment]
OK Posted it in the mailing list. Apologies for any inconvenience.
