### ISSUE TITLE
unit.tls sometimes fails on short read

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1127]
```
.../unit/tls_test.cc(89): error: in "test_x509_client_with_builder_system_trust_multiple": check buf.size() > 8 has failed
```

Failing assertion:
```c++
                            auto f = in.read();
                            return f.then([](temporary_buffer<char> buf) {
                                // std::cout << buf.get() << std::endl;

                                // Avoid passing a nullptr as an argument of strncmp().
                                // If the temporary_buffer is empty (e.g. due to the underlying TCP connection
                                // being reset) passing the buf.get() (which would be a nullptr) to strncmp()
                                // causes a runtime error which masks the actual issue.
                                if (buf) {
                                    BOOST_CHECK(strncmp(buf.get(), "HTTP/", 5) == 0);
                                }
This one >>>                    BOOST_CHECK(buf.size() > 8);
                            });
```

examples:
https://app.circleci.com/pipelines/github/scylladb/seastar/1306/workflows/34276448-c252-4b70-979c-e200e290a024/jobs/2577
https://app.circleci.com/pipelines/github/scylladb/seastar/1309/workflows/9be37ca0-183b-4225-bbdf-a0095be22261/jobs/2619

**Comment by xemul** [comment]
https://app.circleci.com/pipelines/github/tchaikov/seastar/13/workflows/2924b836-4958-46e7-bd26-19ee5916fa2c/jobs/138

```
==523==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
.../tls_test.cc(90): error: in "test_x509_client_with_builder_system_trust_multiple": check result has failed
.../tls_test.cc(91): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.size() > 8 has failed
.../tls_test.cc(92): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.substr(0, 5) == sstring("HTTP/") has failed [ != HTTP/]
.../tls_test.cc(90): error: in "test_x509_client_with_builder_system_trust_multiple": check result has failed
.../tls_test.cc(91): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.size() > 8 has failed
.../tls_test.cc(92): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.substr(0, 5) == sstring("HTTP/") has failed [ != HTTP/]
.../tls_test.cc(90): error: in "test_x509_client_with_builder_system_trust_multiple": check result has failed
.../tls_test.cc(91): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.size() > 8 has failed
.../tls_test.cc(92): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.substr(0, 5) == sstring("HTTP/") has failed [ != HTTP/]
Established connection
Killing server side
Got expected exception
```

@elcallio , :point_up:

**Comment by elcallio** [comment]
I cannot repro the above (I also don't understand why my PR closed this issue - it did not claim to do so - only maybe add some debuggability). I could repro some other network connectivity issues that can be better handled (related to having a local dns proxy probably). But again, the apparent non-exception short read above; no. 

But since I assume the test managed to run the _single_ read from google test, it is probably not related to any connectivity as such (at least not persistently), but maybe the fact that we do 20 connects at once. Still no idea how we get the above. 

I will send some further tweaks to the test, but again, they do not pretend to fix the problem (whatever it is).

**Comment by xemul** [comment]
https://app.circleci.com/pipelines/github/tchaikov/seastar/15/workflows/38ca33cb-41e9-40d8-b4f5-eeca56260f04/jobs/162

```
==524==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
Reactor stalled for 32 ms on shard 0. Backtrace: 0x47394a 0xc4becd 0xc4b355 0xa976f7 0xa90d1d 0xa9079a 0xa91122 0xa97533 0x4251f 0x4418a3 0x43d73d 0x43d4e3 0x4b74cb 0xa083a 0xb8c5c 0xb9137 0xb92e9 0xb9553 0xde9ba 0xedbe4 0xf08aa 0xf0c8b 0x72373 0x15a3673 0x15a35e2 0x15a3542 0x15a34a6 0x15a3409 0x15a3258 0x15a3055 0x15a2dfb 0x945e1a 0x10e62c9
.../tls_test.cc(84): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.size() > 8 has failed
.../tls_test.cc(85): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.substr(0, 5) == sstring("HTTP/") has failed [ != HTTP/]
.../tls_test.cc(84): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.size() > 8 has failed
.../tls_test.cc(85): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.substr(0, 5) == sstring("HTTP/") has failed [ != HTTP/]
.../tls_test.cc(84): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.size() > 8 has failed
.../tls_test.cc(85): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.substr(0, 5) == sstring("HTTP/") has failed [ != HTTP/]
.../tls_test.cc(84): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.size() > 8 has failed
.../tls_test.cc(85): error: in "test_x509_client_with_builder_system_trust_multiple": check buffer.substr(0, 5) == sstring("HTTP/") has failed [ != HTTP/]
Established connection
```

@elcallio , still the same

**Comment by elcallio** [comment]
Did not expect any change. Only simplified the code some more + make it more resilient to run single-case. I might have misread the email notices. I don't suppose anyone managed to get this issue locally?

**Comment by elcallio** [comment]
I managed to reproduce this, though not exactly predictably. But I think I know what it happening: It is stalls in gnutls on certificate verification (first/cold/uncached) combined with the output_stream flush poller. Basically, the flush poller does not get a chance to run due to reactor stall, and the google server, confronted with a connection spending a few seconds (!) idling, simply, benignly, closes the connection and we get no data back.

(Note: the stall traces I get are not decodable, but I am guessing it is gnutls creating them, esp. since strace of the proc running just one of the tests in question does indeed cause a bunch of file IO reading system security stuff). Not sure if ASAN is adding to the delays here...

Some things to argue here: 
1.) Maybe flush poller should be at least _possible_ optionally to disable for a stream? 
2.) We are again seeing gnutls stalls in cert verification. Not great. But we can't really push verification into separate, pre-empted, threads either - they are way to many. This seems to be mainly an issue when using system trust, which makes sense since this probably results in at least only partially cached loading of info from disk (can't 100% determine from the source at just a glance - somewhat convoluted). 

Not sure how to handle this. We can ignore it and just add a retry iff we get 100% empty response. Can disable flush poller for the output stream used, though stalls between connect and output write could probably have the same effect. 
Best would to eliminate the stalls, but not sure how to do that...

**Comment by xemul** [comment]
> 1.) Maybe flush poller should be at least possible optionally to disable for a stream?

It can be done with `output_stream_options.batch_flushes = false`, but socket code sets it to `true` unconditionally

**Comment by elcallio** [comment]
Yes, I know.

**Comment by elcallio** [comment]
Problem with this is potentially addressing a symptom instead of a cause. And as stated above, it might not really fix anything anyway, since a stall between connect and data actually being sent would have the same effect. This is just a test - we can easily handle the problem in test code. But it could very well happen in real code and thus the question really is: should code take into account potentially being delayed enough that a connection is dropped by the other side?

**Comment by xemul** [comment]
> But we can't really push verification into separate, pre-empted, threads either - they are way to many

Why can't we make it in the thread-pool's thread? Even if there are many verifications, let them "stall" in the context of _that_ thread, not reactor.

**Comment by elcallio** [comment]
Problem with that is that it is not _every_ time you get a stall. But pushing verify into a thread pool would not only _always_ add a significant latency, but also make the verify/re-verify logic rather terrible (i.e. cross-thread synchronization required).
And more to the point, I am still not 100% sure exactly _which_ part of verification is causing spurious stalls. Maybe it can be addressed by pushing some inits to less sensitive parts of control flow...

**Comment by elcallio** [comment]
And for the record:  I can only produce these stalls with ASAN turned on -> probably malloc delays causing it...

**Comment by bhalevy** [comment]
> And for the record: I can only produce these stalls with ASAN turned on -> probably malloc delays causing it...

@elcallio any progress?
This is killing us in CI, especially on debug, g++11, c++17

**Comment by elcallio** [comment]
@bhalevy - the linked issue is a coredumpo in scylla. How is that related to this test?

**Comment by bhalevy** [comment]
> @bhalevy - the linked issue is a coredumpo in scylla. How is that related to this test?

I mentioned this issue in https://github.com/scylladb/scylladb/issues/11252 just because of the general frustration pushing PRs to seastar due to this issue, that was blocking https://github.com/scylladb/seastar/pull/1182.
[The scylla issue](https://github.com/scylladb/scylladb/issues/11252) has no direct relevance to this issue.

**Comment by elcallio** [comment]
Aha. Well, thinking on the problem, I realize it really is a user error. There is no way to ever guarantee wall clock time between creating a connection and actually reading it, so the test needs to handle being time-outed by google. Will send a final patch.
