### ISSUE TITLE
net: missing support for a "backlog" parameter of a listen() 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#14]
Currently we don't support this parameter and set the hard coded value (100).

This value is too small for httpd testing on AWS and we have to manually change it to 1000.

We need to prioritize the implementation of a support for a `backlog` listen() parameter.

**Comment by nyh** [comment]
This was fixed by commit c1f20796002571a1de59f5e9ed2aebe7461bfe39.
We now have a `listen_options`, one of them is `listen_backlog`. It still defaults to 100.

I'm not sure whether this default of 100 is good (in scripts/perftune.py we set `/proc/sys/net/core/somaxconn` to 4096, which suggests we expected much higher number to be used in practice), and if this option is visible enough, but at least we have it as an option so we can close this issue.
