### ISSUE TITLE
Deprecate public range print helpers

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#1544]
Seastar exposes two print helpers in https://github.com/scylladb/seastar/blob/58a4e90046da539adb969d26958095660d11bb5d/include/seastar/core/sstring.hh#L749-L782
and a bunch of `to_sstring` helpers in https://github.com/scylladb/seastar/blob/58a4e90046da539adb969d26958095660d11bb5d/include/seastar/core/sstring.hh#L720-L747

This is out of scope for the seastar library.

In particular, the implementation for `operator<<(std::ostream&, const std::unordered_map)` is unusual and conflicts with similar helpers in scylla utils/to_string.hh

cc @avikivity @nyh @tchaikov

**Comment by tchaikov** [comment]
first of all, i am for this change. Seastar is not a formatting library, neither should it help user to print standard containers or even range-like containers or string-like objects -- this is covered by fmtlib already.

currently, we have 4 ways to print a range

1. `fmt::join()` to print a range with customized delimiter
2. `fmt::format()` to print a range. this is also supported by `fmt/range.h`
3. `operator<<(ostream&, ...)` overloads provided by `scylladb/utils/to_string.hh`
4. `to_string()` overloads provided by `scylladb/utils/to_string.hh`
5. `operator<<(ostream&, ...)` overloads provided by `seastar/core/sstring.hh`
6. `to_string()` overloads provided by `seastar/core/sstring.hh`

i think we should consolidate them, and only use a single approach for printing out various objects or container of them -- fmtlib. but we should at least ready Scylla for this change. to make this happen, there is a strong requisite, to make `fmt::is_formatable<Printable>::value` true, where `Printable` is any type which want to print. `fmt/ranges.h` uses this predicate to tell if an element can be printed using its builtin range-like formatter. currently, despite that `seastar::sstring` can be printed using `fmt::format()` either because of `FMT_DEPRECATED_OSTREAM` or because of the `fmt::formatter<seastar::sstring>` partial specialization, we cannot print `std::pair<int, sstring>` or `std::unordered_map<int, sstring>` using Seastar's builtin support for range-like container. because `!detail::has_fallback_formatter<T, Char>::value>` is false, so is `fmt::is_formatable<sstring>::value`. see !detail::has_fallback_formatter<T, Char>::value>. the reason why `has_fallback_formatter<>` is true is that we have `FMT_DEPRECATED_OSTREAM` defined in scylla.

we need to use a bottom-up approach to achieve this goal:

1. replace all `os << foo << " and " << bar` with `fmt::print(os, "{} and {}", foo, bar)`
2. use `fmt::join()` for printing containers.
3. use specialization of `fmt::formatter<Printable>` in the place of `ostream<<(ostream&, const Printable&)`
4. if we have to keep `ostream<<(..)`, we can implement it using the former.
7. repeat  step 1,2 and 3 until we don't depend on `FMT_DEPRECATED_OSTREAM` anymore
8. drop  `FMT_DEPRECATED_OSTREAM` from `configure.py`
9. use the builtin range-like formatting in the place of `fmt::join()` where the delimiter fulfills our needs

as scylla is a large scale project, we might want to address this in multiple iterations.

**Comment by bhalevy** [comment]
@tchaikov the above sounds like a solid plan

**Comment by avikivity** [comment]
Agree with the plan. Note that FMT_DEPRECATED_OSTREAM isn't in seastar, IIRC.

**Comment by tchaikov** [comment]
No, it's not in Seastar. But it prevents Scylla from using fmtlib's builtin range and tuple formatters with our types like sstring. So we need to fix Scylla first and then drop these helpers.

**Comment by tchaikov** [comment]
i am copying this issue and the plan above to scylla. so when we have PRs address it, we can associate these PRs to the scylla issue, as Avi pointed out, `FMT_DEPRECATED_OSTREAM` is not in Seastar.  a lot of work is on the Seastar applications' side, once they drop the dependencies on these helpers, we can safely deprecate or better off completely remove them.

**Comment by bhalevy** [comment]
@nyh I can understand seastar proving printers for data structures it defines, but why would it provide pretty printers for stl types?

**Comment by gleb-cloudius** [comment]
> @nyh I can understand seastar proving printers for data structures it defines, but why would it provide pretty printers for stl types?

Because if nobody else provides them then printing containers becomes a PITA.

**Comment by bhalevy** [comment]
> > @nyh I can understand seastar proving printers for data structures it defines, but why would it provide pretty printers for stl types?
> 
> Because if nobody else provides them then printing containers becomes a PITA.

Modern fmt library version provide helpers for containers / ranges.
See https://github.com/scylladb/seastar/issues/1544#issuecomment-1475243969
