### ISSUE TITLE
current_tasktrace() segfaults when run in a task resumed by condition_variable

### ISSUE THREAD

**Issue by michoecho** [scylladb/seastar#1599]
`condition_variable::awaiter` implements the coroutine resumption after `signal()` by scheduling itself as a task which resumes the coroutine. The awaiter itself is (usually) allocated inside the coroutine frame, and dies after its containing `co_await` expression is resumed.

This is a problem, because the reactor expects tasks to stay alive while they are running — it saves a pointer to the current task in `reactor::_current_task`, which is used to find the parent task when printing the tasktrace. Because the `awaiter` task dies immediately after returning control to its parent, `reactor::_current_task` is left pointing to some garbage in the coroutine frame and `current_tasktrace()` will segfault when used before the next task switch.

Observed in https://github.com/scylladb/scylladb/issues/13368

**Comment by michoecho** [comment]
@avikivity We might want to backport this to 5.2

**Comment by mykaul** [comment]
> @avikivity We might want to backport this to 5.2

How come we don't have the 'Backport Candidate' label for this project?

**Comment by avikivity** [comment]
Seastar has its own (very primitive) branching policy, and its branches are unrelated to scylladb branches.

The way we manage seastar backports in scylladb is to create a scylladb issue that describes the problem, mark it fixed in the scylladb commit that moves the seastar submodule, and then that issue gets marked with the backport candidate label normally.
