### ISSUE TITLE
flaky unit test httpd_test :: test_100_continue

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#1645]
The test test_100_continue in tests/unit/httpd_test.cc failed twice today, in two circleci runs:

https://app.circleci.com/pipelines/github/avikivity/seastar/252/workflows/7fa40da2-16d2-4b2d-88a2-dfe266a083b4/jobs/857
https://app.circleci.com/pipelines/github/avikivity/seastar/252/workflows/7fa40da2-16d2-4b2d-88a2-dfe266a083b4/jobs/855

The error is the case in both:
```
/home/circleci/project/tests/unit/httpd_test.cc(810): fatal error: in "test_100_continue": critical check std::string(resp.get(), resp.size()).find("100 Continue") != std::string::npos has failed [18446744073709551615 == 18446744073709551615]
```

I don't know how often this test fails (I don't think circleci keeps a log of per-test failures?) but I found another - different - failure of the same test in https://github.com/scylladb/seastar/issues/1190. 

I am not familiar enough with this test to guess if this is a test bug or a real bug discovered by the test. @wmitros, you wrote this test (and the feature it tests), can you please take a look?

**Comment by xemul** [comment]
The root-cause is that test writes several requests in a loop and reads back whatever arrives from server with a single `input_strea<>::read()` call. So at some point server's response is written in two parts so test loop next iteration instead of reading new server reply continues reading previous reply's 2nd part
