### ISSUE TITLE
on_internal_error doesn't log an error when not aborting

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#1648]
[this issue is opened for backporting purposes]

Up until 40c03bb8ddef9f7097cca798ff55cc3110cbcd85, on_internal_error would log the error only when abort_on_internal_error is set, right before aborting.

On the other path, when throwing the exception, it would print nothing to the log.
This is wrong. The internal error must be visible as we're on a very high risk path and recovering from that error is not always possible.

**Comment by bhalevy** [comment]
Fixed with 40c03bb8ddef9f7097cca798ff55cc3110cbcd85

**Comment by nyh** [comment]
For posterity - the link above is not a valid Seastar commit.
I think this issue is a duplicate of https://github.com/scylladb/seastar/issues/955, and the fix is PR https://github.com/scylladb/seastar/pull/1121 commit https://github.com/scylladb/seastar/commit/84b042759046259c39022abcdefc56ee9110d524
