### ISSUE TITLE
Use 'mq-deadline' I/O scheduler (instead of 'none') where supported

### ISSUE THREAD

**Issue by mykaul** [scylladb/seastar#1704]
To the best of my knowledge, it should be a better scheduler, in the sense that it strives to provide consistent latency ('fairness') among requests. We currently (https://github.com/scylladb/seastar/commit/87ab62f7d2370234c2ed8ffc8073e3fe1281a1cf ) use 'none'.
(Or do we prefer 'none' so it won't interfere with Seastar's I/O scheduler ?)

**Comment by travisdowns** [comment]
> (Or do we prefer 'none' so it won't interfere with Seastar's I/O scheduler ?)

That's how I understand it (I'm not from Scylla): by the time the IOs are released from Seastar's IO scheduler it is mostly expected that they will complete straight away because the IO scheduler already ensures that the disk is not overloaded and hence does not have queuing (beyond what is necessary for full throughput).

So an additional layer of IO scheduling at the block layer is mostly not useful.

Of course, not everyone is running with properly tuned io properties, so it may be useful there.
