### ISSUE TITLE
io_queue::queued_requests() is called from non-coordinator causing a crash

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#177]
reactor registers the following counter, which calls `_io_queue->queued_requests()`:

```
            scollectd::add_polled_metric(scollectd::type_instance_id("reactor"
                    , scollectd::per_cpu_plugin_instance
                    , "gauge", "queued-io-requests")
                    , scollectd::make_typed(scollectd::data_type::GAUGE,
                        [this] { return _io_queue->queued_requests(); } )
            ),

```

`_io_queue` may point to an object which is owned and mutated by a different shard (_io_coordinator).  `io_queue::queued_requests()` calls `fair_queue::waiters()`, which calls `semaphore::waiters`, which calls `chunked_fifo::size()`, which is not thread-safe. Which suggests that queued_requests() should only be called on _io_coordinator, but it's not.

This may cause a crash in `chunked_fifo::size()`:

```
    if (_front_chunk == nullptr) {
        return 0;
    } else if (_back_chunk == _front_chunk) {
        // Single chunk.
        return _front_chunk->end - _front_chunk->begin;
    } else {
>>>>>> SIGSEGV, _front_chunk == nullptr
        return _front_chunk->end - _front_chunk->begin
                +_back_chunk->end - _back_chunk->begin
                + (_nchunks - 2) * items_per_chunk;
    }
```

**Comment by tgrabiec** [comment]
Perhaps we shouldn't have this counter at all, and just have per-io-queue counters?

**Comment by slivne** [comment]
strange that it did not happen before ....

@avikivity any input ?

**Comment by glommer** [comment]
@tgrabiec I agree that the counter is unnecessary. I have used it heavily in the past, but that was just because we were already using it and it was convenient to leave it as is in my dashboards.

But we need to be sure that this will indeed fix the issues you see. queued_requests() is also used from submit_io(), although in this case we do that inside submit_to -> so we are safe.

Are the other metrics, the queue specific ones, safe? We have 4 metrics per queue, and they all use members of priority_class_data exclusively. Each priority_class_data, belongs to a specific I/O Queue. So cross-shard access here is definitely possible. But the types involved are all POD types, with the exception of an std::chrono -> so we should be good.

I will remove the problematic counter.

**Comment by glommer** [comment]
@slivne The change that moved the semaphore to chunked fifos is relatively new. Before that we were using data types in which this either couldn't happen or it was so rare that never did (I would bet on the first hypothesis)

**Comment by glommer** [comment]
@tzach if we are removing a metric, this should be described in the changelogs. Since you are already talking about the ones we are adding, it is a quite convenient opportunity to just say we are replacing it.

**Comment by tzach** [comment]
@glommer agree. If you do, let me know and I will add it.

**Comment by tgrabiec** [comment]
@glommer What I meant in my comment was that instead of a per-reactor counter, we should move to to a per-io-queue counter, where each io-queue registers it on the shard which owns it.

**Comment by glommer** [comment]
@tgrabiec I was responding to the comment in which you said "Perhaps we shouldn't have this counter at all, and just have per-io-queue counters?". @avikivity seems to believe the counter is welcome, though. So I'll send an updated patch that keeps it, but in the coordinator only.
