### ISSUE TITLE
unit test failures when running in none privileged containers

### ISSUE THREAD

**Issue by a16bitsysop** [scylladb/seastar#1826]
Running the tests in none privileged containers results in lots of errors like:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not setup Async I/O: 1048576. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr (Function not implemented). Try increasing that number or reducing the amount of logical CPUs available for your application
qemu: uncaught target signal 6 (Aborted) - core dumped

```

I think this is happening in the alpine CI as well which builds seastar and runs tests in none privileged containers.

Log from building for aarch64 on x86_64 with docker and qemu

[aarch64-LastTest.log](https://github.com/scylladb/seastar/files/12597121/aarch64-LastTest.log)

**Comment by tchaikov** [comment]
i think this problem is in QEMU. see

- https://bugs.launchpad.net/qemu/+bug/1884719 , and 
- https://gitlab.com/qemu-project/qemu/-/issues/210

the combination of docker + QEMU is great for testing aarch64 applications on an amd64 host. but IMHO, this is not a typical setting of Seastar which is used to built highly paralleled system with intensive i/o. so probably it's not that urgent to fix this issue.

but if we are interested in why, here is my preliminary analysis. QEMU is a dynamic translator. it interpret the instruction set of the executable being executed to that on the host. and it even translate the syscalls. and it uses a giant table for dispatching the `_NR_*` numbers. the table is generated from linux kernel source. but somehow the `_NR_io_setup` is still 0. see https://github.com/qemu/qemu/blob/9ef497755afc252fb8e060c9ea6b0987abfd20b6/linux-user/aarch64/syscall_nr.h#L9 while the `_NR_io_setup` in linux 's aarch64 is 243 see https://github.com/torvalds/linux/blob/3669558bdf354cd352be955ef2764cde6a9bf5ec/arch/arm64/include/asm/unistd32.h#L499 .

the commit message of https://github.com/qemu/qemu/commit/3a2f19b7ee3abbba5fd6f3e02fcdd26dc392a990 claims that the QEMU's syscall table was generated 2 years ago from Linux v5.13. probably there is a bug in https://github.com/qemu/qemu/blob/master/scripts/gensyscalls.sh, so that the definition of https://github.com/torvalds/linux/blob/3669558bdf354cd352be955ef2764cde6a9bf5ec/include/uapi/asm-generic/unistd.h#L33 overrides the one defined in `arch/arm64/include/asm/unistd32.h`.

i need to take a closer look later.

**Comment by tchaikov** [comment]
i am closing this as "won't fix". it's a bug in QEMU.
