### ISSUE TITLE
Failure to build seastar - libfmt-dev version issue

### ISSUE THREAD

**Issue by kfirgollan** [scylladb/seastar#1896]
Latest seastar build fails on compilation issue
```
381.1 [213/278] Building CXX object tests/unit/CMakeFiles/test_unit_sstring.dir/sstring_test.cc.o
381.1 FAILED: tests/unit/CMakeFiles/test_unit_sstring.dir/sstring_test.cc.o
381.1 /usr/bin/clang++-15 -DBOOST_ALL_DYN_LINK -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_BROKEN_SOURCE_LOCATION -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SSTRING -DSEASTAR_TESTING_MAIN -DSEASTAR_TESTING_WITH_NETWORKING=1 -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_TYPE_ERASE_MORE -I/seastar/tests/unit -I/seastar/src -I/seastar/include -I/seastar/build/dev/gen/include -O2 -UNDEBUG -Wall -Werror -Wimplicit-fallthrough -Wdeprecated -Wno-error=deprecated -gz -U_FORTIFY_SOURCE -Wno-error=unused-result "-Wno-error=#warnings" -fstack-clash-protection -std=gnu++20 -MD -MT tests/unit/CMakeFiles/test_unit_sstring.dir/sstring_test.cc.o -MF tests/unit/CMakeFiles/test_unit_sstring.dir/sstring_test.cc.o.d -o tests/unit/CMakeFiles/test_unit_sstring.dir/sstring_test.cc.o -c /seastar/tests/unit/sstring_test.cc
381.1 /seastar/tests/unit/sstring_test.cc:28:10: fatal error: 'fmt/std.h' file not found
381.1 #include <fmt/std.h>
381.1          ^~~~~~~~~~~
381.1 1 error generated.
```

Seems like the following commit introduced it
https://github.com/scylladb/seastar/commit/e6a848b7d5524a74018d43e34a1582015a4d8c5b
@avikivity / @nyh 

I inspected the files packaged in `libfmt-dev`, and verified `fmt/std.h` is not present.
```
$ apt-file list libfmt-dev
libfmt-dev: /usr/include/fmt/args.h
libfmt-dev: /usr/include/fmt/chrono.h
libfmt-dev: /usr/include/fmt/color.h
libfmt-dev: /usr/include/fmt/compile.h
libfmt-dev: /usr/include/fmt/core.h
libfmt-dev: /usr/include/fmt/format-inl.h
libfmt-dev: /usr/include/fmt/format.h
libfmt-dev: /usr/include/fmt/locale.h
libfmt-dev: /usr/include/fmt/os.h
libfmt-dev: /usr/include/fmt/ostream.h
libfmt-dev: /usr/include/fmt/printf.h
libfmt-dev: /usr/include/fmt/ranges.h
libfmt-dev: /usr/include/fmt/xchar.h
libfmt-dev: /usr/lib/x86_64-linux-gnu/cmake/fmt/fmt-config-version.cmake
libfmt-dev: /usr/lib/x86_64-linux-gnu/cmake/fmt/fmt-config.cmake
libfmt-dev: /usr/lib/x86_64-linux-gnu/cmake/fmt/fmt-targets-none.cmake
libfmt-dev: /usr/lib/x86_64-linux-gnu/cmake/fmt/fmt-targets.cmake
libfmt-dev: /usr/lib/x86_64-linux-gnu/libfmt.so
libfmt-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/fmt.pc
libfmt-dev: /usr/share/doc/libfmt-dev/README.Debian
libfmt-dev: /usr/share/doc/libfmt-dev/changelog.Debian.gz
libfmt-dev: /usr/share/doc/libfmt-dev/copyright
```

Tested on ubuntu 22
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

I think that another important topic to note here is that this passed build on the CI, I believe this is because the CI is using an image which doesn't use the [`install-dependencies.sh`](https://github.com/scylladb/scylladb/blob/master/install-dependencies.sh) - [docker.io/scylladb/seastar-toolchain:2023-08-13](https://github.com/scylladb/seastar/blob/master/.circleci/config.yml#L21C150-L21C197)

This container image contain various other packages, which are not included in the seastar scripts
https://github.com/scylladb/scylladb/blob/master/tools/toolchain/Dockerfile

**Comment by tchaikov** [comment]
the CI uses the docker image created from [Dockerfile](https://github.com/scylladb/scylladb/blob/master/tools/toolchain/Dockerfile), which is based on ubuntu kinetic. and ubuntu kinetic provides [libfmt-dev 9.0.0](https://packages.ubuntu.com/kinetic/libfmt-dev). while jammy ships [libfmt-dev 8.1.1](https://packages.ubuntu.com/jammy/libfmt-dev). but we only require fmt v5.0.0, see https://github.com/scylladb/seastar/blob/b1c209b0b7ee550d12faab4e9ae291655b621c14/cmake/SeastarDependencies.cmake#L128 

i wanted to bump up the minimal supported fmtlib version to 8.0.0 in #1601, but it seems it's too soon to urge our user to upgrade their fmtlib. so we need to support fmt v5.0.0 at this moment.

we include `fmt/std.h` for testing the formatter to see if it works with the one formatting `std::optional<>`. but this header was introduced in fmt v9.0.0, and the support of `std::optional<>` was introduced in fmtlib v10.0.0. fortunately, the ranges support has been around since 5.0.0. so we are safe.

created #1897 to address this FTBFS.
