### ISSUE TITLE
Replace zlib with zlib-ng

### ISSUE THREAD

**Issue by mykaul** [scylladb/seastar#1898]
Split of https://github.com/scylladb/seastar/pull/1637#issuecomment-1531399547

zlib-ng (https://github.com/zlib-ng/zlib-ng ) is supposed to be API compatible with zlib (may need ZLIB_COMPAT compilation flag!) but faster.

**Comment by nyh** [comment]
@mykaul do you know where Seastar actually uses zlib?
I don't see any direct usage of this library anywhere in Seastar. Did we inherit the need from it from some other library, e.g., openssl?

In any case, I don't understand what this issue is about - Seastar does not **include** zlib, or install it in install-dependencies.sh, so where do we "replace" zlib?

I see zlib *is* mentioned in `cooking_recipe.cmake`, but is this recipe actually used? By whom?

**Comment by mykaul** [comment]
Strange - I couldn't find where it's used either :-/ 

Then perhaps we should:
1. Remove it from Seastar
2. Move this to Scylla, which does use zlib in some places (although I'm not sure where exactly, as it does mix the usage with libdeflate!)

**Comment by mykaul** [comment]
@tchaikov - any idea if we can just remove zlib from Seastar? (perhaps it's used by DPDK?)

**Comment by tchaikov** [comment]
@mykaul yeah, dpdk it is:

```console
$ rpm -ql zlib-devel | grep include
/usr/include/zconf.h
/usr/include/zlib.h
$ cd dpdk
$ git grep -E '(zlib|zconf).h'
app/test/test_compressdev.c:#include <zlib.h>
drivers/compress/zlib/zlib_pmd_private.h:#include <zlib.h>
drivers/net/bnx2x/bnx2x.c:#include <zlib.h>
drivers/net/qede/base/ecore.h:#include <zlib.h>
```

**Comment by mykaul** [comment]
OK, closing then.

**Comment by tchaikov** [comment]
i think it is used as the software implementation of [compressdev](https://doc.dpdk.org/guides/prog_guide/compressdev.html), and its hardware accelerated counterpart is QAT.

probably we can drop it as we are not using it. or encourage the upstream to switch to zlib-ng if we plan to use this API in our application, but i doubt that we are going in this direction.

**Comment by tchaikov** [comment]
#1901 was created to address this.
