### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mcraveiro** [scylladb/seastar#196]
Hi Seastarers,

Thanks for an extremely useful piece of software. Bit of a general question, couldn't find it in the docs - apologies if I've missed it. Is there any windows support at present (even if limited, Posix only etc). If not, are there any major reasons why this cannot be done.

Cheers

Marco

**Comment by avikivity** [comment]
There is no Window support at present, but we'll accept patches. Challenges would be to get the compiler to accept the code (gcc on windows ought to work) and a few Linuxisms that are in the memory management and thread binding code.

Since we use hwloc, extending use of that would reduce Linux dependencies (it supports memory binding etc), and #ifdefs in strategic locations.  It's not a lot of work but requires some system-level knowledge.  Try it out and see.

**Comment by mcraveiro** [comment]
Thanks @avikivity. I'll close the ticket for now and reopen it when I get round to working on this.
