### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by hustnn** [scylladb/seastar#224]
[171/283] LINK build/debug/apps/iotune/iotune
FAILED: g++-5  -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -I build/debug/gen -g -Wl,--no-as-needed   -fvisibility=hidden -pthread  -o build/debug/apps/iotune/iotune build/debug/apps/iotune/iotune.o build/debug/apps/iotune/fsqual.o build/debug/core/resource.o -laio -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -lgcc_s -lunwind -lxenstore -lhwloc -lnuma -lpciaccess -lxml2 -lz -lasan -lubsan  
/usr/bin/ld: unrecognized option '--push-state'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
[171/283] CXX build/release/apps/memcached/memcache.o
ninja: build stopped: subcommand failed.

Anyone met this problem?

**Comment by hustnn** [comment]
I use -fuse-ld=gold to solve this issue.

Thanks.

**Comment by isyes** [comment]
I encounter the same problem, It's maybe a GCC-7 bug, I add --ldflags='-fuse-ld=gold' when run configure.py

**Comment by nyh** [comment]
This is apparently a gcc 7 bug, fixed in updates to most distros - see for example discussion in https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed

I think we should probably close this issue. It should be possible to add code in configure.py to check for this bug and work around it (e.g., by using gold) but it's probably not worth the hassle.

Alternatively, we might consider using gold whenever it exists, which will also help in this bug. IIRC we already recommend making gold the default "ld" to get a faster linking, and we could use it even if it's not the default "ld".
