### ISSUE TITLE
circleci CI was removed but it's still being reported

### ISSUE THREAD

**Issue by tchaikov** [scylladb/seastar#2251]
we need to remove seastar's CircleCI pipeline from the CircleCI. see https://app.circleci.com/projects/project-dashboard/github/scylladb/.

**Comment by nyh** [comment]
@avikivity it appears I don't have a CircleCI account any more (or I never did). Can you please remove this pipeline, or try to recall who has the permissions to do it?

**Comment by avikivity** [comment]
Why do we need to remove the pipeline?

**Comment by nyh** [comment]
> Why do we need to remove the pipeline?

Right now all Seastar pull requests (e.g., see https://github.com/scylladb/seastar/pull/2252) "fail" the tests because:
![image](https://github.com/scylladb/seastar/assets/584227/d4f9c2a6-36c0-4e10-97df-6f51b39887ca)

Apparently, somehow the circleci is registered to receive updates on Seastar, and when it sees a new pull request, it tries to read the circleci configuration from our repository, and because the file is gone (we deleted it), it writes a "failure" to the project. I have no idea how we can disable all of this on the github side, so I guess we need to do it on the circleci side. But if you know of a better way to fix this, go ahead.

**Comment by tchaikov** [comment]
i think we should disable it on the circleci side. i just managed to do this on my own seastar repo on github.

**Comment by avikivity** [comment]
Did circleci remove our configuration?

**Comment by nyh** [comment]
> Did circleci remove our configuration?

We removed our configuration, in commit 223eccf09c3e0835e61ba737fdc9056a1112eb23.
But now circleci spams each of our PRs with the message that it can't find our configuration. It appears (?) we need to tell circleci to stop doing that, but only the person who set it up initially and has the right permissions can do it.

**Comment by avikivity** [comment]
Ah, we replaced a free service with a paid service.

**Comment by nyh** [comment]
> Ah, we replaced a free service with a paid service.

I was sure you saw this was happening...

First, github actions is supposedly **free** for public projects. I was surprised, but it seems to be true.
Second, circleci was (supposedly) boycotting some of our developers because of the country where they originate, and not testing their patches. This was very frustrating.
This is why @tchaikov proposed to switch from circleci to github actions, and I thought it was a good idea. Do you disagree?

**Comment by tchaikov** [comment]
since it disappeared. closing.
