### ISSUE TITLE
accept() should check if the queue is empty.

### ISSUE THREAD

**Issue by xnhp0320** [scylladb/seastar#2351]
In the tcp.hh file, the accept function:
```c++
          future<connection> accept() {
               return _q.not_empty().then([this] {
                   return make_ready_future<connection>(_q.pop());
               });
           }
```

the *not_empty()* could schedule a task however, if at somewhere else someone just calls the listener's *abort()* method, the queue becomes empty, and when the task is executed, the assertion in pop() will fail.

Better to check it again, if _q is empty and ex is set, return an exception future.

**Comment by bhalevy** [comment]
@lersek please look into this.
Cc @paszkow

**Comment by lersek** [comment]
Apologies, I don't understand how the described symptom can occur.

If `not_empty()` returns an as-yet unresolved future, then the `_not_empty` member will be set to a `void` promise. In turn, `abort()` stores its input exception into `_not_empty`. Thereafter, the lambda with the `pop()` call should never be invoked, as the lambda is chained with `.then()` to the future originally returned by `not_empty()` -- and the latter resolves with an exception due to `abort()`, as described above. Thus the future returned by `accept()` should resolve with the same exception.

Where you say *check [...] again [...] if `_q` is empty and `ex` is set*, within the lambda, that location should be unreachable to begin with, when the future output by `not_empty()` resolves to an exception, due to an intervening `abort()` call.

@xnhp0320 do you have a small self-contained reproducer for this symptom? Or else, if you only have a large reproducer that you can't share, can you perhaps insert debug messages into `not_empty()`, `abort()` and `pop()`, and share the log?

Also can you confirm that you are not accessing these objects from multiple (heavy-weight / posix) threads at the same time? Thanks.

**Comment by xnhp0320** [comment]
When the `q` is not empty, the promise of `_not_empty` is set, and this means a task is added into the run-queue, however the task might not be running immediately. Now, the `_not_empty` is set into another void promise.

```c++
template <typename T>                                                                                                                                                                  inline
   void queue<T>::notify_not_full() {
       if (_not_full) {
           _not_full->set_value();
           _not_full = compat::optional<promise<>>();
       }
   }
```

Suppose in somewhere, someone calls `q->abort()` in-place, this will set promise into an exception, however, the previous task is already added into the task queue. When `run_some_tasks()` is called, the task will be executed unconditionally.

**Comment by lersek** [comment]
@tchaikov Can you please take a look at this ticket?

@xnhp0320's response suggests that seastar does not deal well with the situation when a task is "invalidated" (= the promise is set to exception state) after it is queued, but before it is executed. If it *can* indeed happen, then I think we need a more general pattern for dealing with it, than just ad-hoc, repeated checks of application-specific invariants, in the chained lambdas that should, in fact, not even be *reached*. "Oops, I shouldn't have been executed, let me just bail out of the lambda early" seems like a wrong answer; the right answer is *not to enter the lambda*. Sort of de-queue (or mark for skipping) the chained-on future instead.

I assume that, if this "invalidation in flight" can indeed happen, then it must have been encountered before, and I'd expect SeaStar to offer a general pattern for applications to deal with it. Thanks!

**Comment by bhalevy** [comment]
That's pretty much what we're doing in `pop_eventually`:
https://github.com/scylladb/seastar/blob/3fdb59979aa919face21390d517846258a83c4aa/include/seastar/core/queue.hh#L235-L240

**Comment by xnhp0320** [comment]
> That's pretty much what we're doing in `pop_eventually`:
> 
> https://github.com/scylladb/seastar/blob/3fdb59979aa919face21390d517846258a83c4aa/include/seastar/core/queue.hh#L235-L240
> 
> The extra check is for exception, not for the queue begin empty though. If there could be a race between multiple consumers that may wait on `not_empty()`, and one item is inserted, then they need to check if there's anything in the queue after `not_empty()` resolves, but I'm not sure if that's the case here.
> 
> See documentation,
> 
> https://github.com/scylladb/seastar/blob/3fdb59979aa919face21390d517846258a83c4aa/include/seastar/core/queue.hh#L94-L99

I think this api can solve my problem. 
Since the race here is only between `accept_abort` and `accept`, so checking the `_ex` is  enough. 

Thanks everyone!

**Comment by tchaikov** [comment]
i am reopening this issue. as it is not fixed.

**Comment by xnhp0320** [comment]
> i am reopening this issue. as it is not fixed yet.

agree, `accept()` should use `pop_eventually()`.

**Comment by lersek** [comment]
> If there could be a race between multiple consumers that may wait on `not_empty()`, and one item is inserted, then they need to check if there's anything in the queue after `not_empty()` resolves, but I'm not sure if that's the case here

Based on the documentation, I believe this use case is expicitly unsupported:

https://github.com/scylladb/seastar/blob/e14181f162649176d457e4b8f490fc13eb46489b/include/seastar/core/queue.hh#L34-L35

**Comment by lersek** [comment]
So general lesson to me: counter to my expectation, tasks *can* go stale between their queueing and execution (i.e. the invariant that implied their queueing may be invalidated before execution, *and* that situation has to be handled within the particular task itself).
