### ISSUE TITLE
Add Seastar options to export metrics rather than require apps to start a server externally

### ISSUE THREAD

**Issue by tomershafir** [scylladb/seastar#2415]
Add Seastar options to export metrics and make its critical aspect of visibility much easier to use, rather than require each application to duplicate the server setup themselves.

Applications that need more control can still do it externally. This would be the default too for backward compatibility.

I suggest the options will not be bound to Prometheus (even though its de facto standard), but have them generalized for pull model, like `metrics_server_path`, `metrics_server_port`, `metrics_server_address`, and neutral ones like `metrics_prefix`. Then if you change the protocol can add another `metrics_protocol` option, and if there is a push model can add a `metrics_target_url` option.

Let me know wdyt and if I should add it.

**Comment by nyh** [comment]
Why is having "options" better or easier for application developers than writing code that starts the metrics server?

If the current API for starting a Prometheus server is too elaborate, perhaps requiring a dozen lines of boilerplate code, then this startup code should be documented (I think it isn't...), and perhaps even simplified to be shorter and easier to use (and easier to explain in documentation) - but it can still be code in the application's source code. Not an "option".

Code has several benefits over options:

1. It's easy to support multiple use cases - you mentioned different ports, different protocols, push vs pull - there can be functions and parameters to control all of these. When you make them command-line options, you start have dozens of these options and constantly add more of them as new combinations of setups become needed.
2. The application may want to start the metrics server only after starting other things (e.g., setting up its own server) or after reading more configuration options from a file. When code starts the server, it's easy to do. When Seastar has builtin options to start the server, it will start at the wrong time and may not have the proper knowledge of which port to use, and so on.
3. One can write a stand-alone application that does not need a configuration file to work correctly.

**Comment by tomershafir** [comment]
I understand that code has benefits of flexibility and as I mentioned devs that need custom logic will still be able to write code. However, code is usually harder to write than options.  `apps/httpd/main.cc` has 30-40 lines of code for metrics. Its also not documented. I think my claim stays valid even if I add documentation and reduce boilerplate. I think about the common case:

1. The common case is standard protocols, like Prometheus or OTLP over TCP/IP. L2 and L3 protocols obviously change very slow, and almost effectively static. In addition, the abstract model of a metric is also effectively static (something like {name,time,value,labels}) so I think L4 protocols shouldn't explode too, especially given the Prometheus and OTEL efforts.

2. The common model goes as follows: seastar reports its own metrics, and the app can report custom metrics. They are logically distinct and reported in different ways (as currently afais seastar doesnt support custom metrics). This way, I think it makes sense that seastar can totally own its metrics without user code, and users would usually just expect seastar to report its metrics without code but with configuration.

3. One can probably say the inverse - I can write the app without this boilerplate code.

**Comment by tomershafir** [comment]
But fixing the docs and reducing boilerplate would be much better than now, too.

**Comment by nyh** [comment]
> I understand that code has benefits of flexibility and as I mentioned devs that need custom logic will still be able to write code. However, code is usually harder to write than options. `apps/httpd/main.cc` has 30-40 lines of code for metrics.

`grep prometheus seastar/apps/httpd/main.cc` yields "only" 20 lines, so of which are error messages and configuration which is needed even in your solution. So,

> Its also not documented.

I think this is the biggest problem. If tutorial.md or something had a dozen lines you could cut and paste into your application, it doesn't seem to be too hard. In general tutorial.md really needs A LOT more work until it becomes a usable Seastar book.

>     2. The common model goes as follows: seastar reports its own metrics, and the app can report custom metrics. They are logically distinct and reported in different ways (as currently afais seastar doesnt support custom metrics). This way, I think it makes sense that seastar can totally own its metrics without user code, and users would usually just expect seastar to report its metrics without code but with configuration.

I don't think it really works this way in practice. It is true that Seastar can **count** its own metrics, but no application would want Seastar to go ahead and open its own port to **report** its own metrics separately from how the application reports its own metrics. The results of this independent reporting can range from annoying to an outright security hole (exposing information that the application might not have wanted to expose). Applications will normally want to open a single port (which they configure) or some other mechanism (push?) to report both Seastar's and their own metrics in one unified manner which the application believes is good and secure.  I believe an application would want to do this configuration - in code - at a place it decides during its initialization, after reading its own configuration, and so on, and not automatically based on command-line parameters.

>     3. One can probably say the inverse - I can write the app without this boilerplate code.

There is a general tension in software development between doing more things in code or doing more things in text files / configuration files / scripting languages. In Seastar the "default" way to do things is in C++ code - not in YAML files. You are supposed to build your applications from pieces the library supplies you using C++ code. YAML snippets may be convenient for very specific cases, but I'm afraid may be too limited in other cases.

Maybe if you go ahead and do this, the result will be undeniably beautiful and all the reviewers will love it. But since you asked this question before writing the code, I can only **guess** that it won't be beautiful. But you are still free to push ahead and prove me wrong!
