### ISSUE TITLE
Execution of tasks may become inefficient when more than _max_task_backlog tasks are active

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#302]
When `need_preempt()` becomes true, ready continuation chains are broken, so that pollers can run soon. However, as long as there is more than `_max_task_backlog` tasks in the queue, the task executing loop will not exit. Preemption is still not lifted, so ready continuation chains are still broken. As a result, tasks will execute in a slow mode in which every `then()` results in task allocation and backtracing (bad for cache locality).

**Comment by avikivity** [comment]
Good catch.

**Comment by duarten** [comment]
What's the rationale for `_max_task_backlog`? Shouldn't we trust the upper layers of the system detect overload and apply back pressure or load shedding?

**Comment by avikivity** [comment]
Good question. The upper layers have limited ability to protect the lower layers, because a single upper layer task can translate to thousands of reactor tasks, possibly on a different shard. If you consider the worst case, you'll severely limit concurrency. If you consider the average case, the worst case will eat you.

**Comment by avikivity** [comment]
Of course, _max_task_backlog predates many of these upper layer protections, so that wasn't the motivation when it was written.

**Comment by avikivity** [comment]
Patch posted.
