### ISSUE TITLE
List projects that use seastar

### ISSUE THREAD

**Issue by ddorian** [scylladb/seastar#310]
Only ones I know are: 

https://github.com/fastio/pedis
http://senior7515.github.io/smf/

**Comment by nyh** [comment]
This is not a Seastar bug or enhancement request, so please close it and move the discussion to the seastar-dev mailing list (unfortunately, I don't have the permissions to do this myself. Annoying github bug tracker limitations...).

But since you asked: The biggest user of Seastar (and the reason why it was written in the first place) is ScyllaDB, an Apache Cassandra clone with 10-fold improvement in throughput and also lower latency. There are several other projects which people talked about the mailing list, but I don't know their name or status.
