### ISSUE TITLE
How can I catch the exception in client when server shut down by exception

### ISSUE THREAD

**Issue by shanshanpt** [scylladb/seastar#355]
There is a client and a server, when I kill the server process, how to catch the exception in the client? I try to use "then_wrapped" follow the write and the read function, but I can't catch the exception. Seastar just report_failed_future(...).
example:
write.then_wrapped([] (auto&& f) {
   try {
        f.get();
   } catch(std::exception& ex) {....}
});
Thanks.

**Comment by noahdesu** [comment]
Disclaimer: I'm very new to Seastar.

It's a little hard to tell from your example code what's going on, but from your description I think the answer is that exceptions are not propagated between clients and servers. When you kill the server, your client will observe broken sockets, etc..., so you have to handle those cases.

**Comment by shanshanpt** [comment]
@noahdesu
thanks. The problem is where to catch the exception. I try to catch（use then_wrapped）the exception in many functions. 
for example：
if the server shut down when the client exec write function，client will coredump.

**Comment by tgrabiec** [comment]
Normally write()  or close() should return a failed future. If you get
ignored failed future or a core dump, it 's probably a bug, either in your
code, or in seastar. You could try the debug mode build with sanitizers to
catch the bug.


08.11.2017 1:05 AM "shanshanpt" <notifications@github.com> napisał(a):

@noahdesu <https://github.com/noahdesu>
thanks. The problem is where to catch the exception. I try to catch（use
then_wrapped）the exception in many functions.
for example：
if the server shut down when the client exec write function，client will
coredump.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/seastar/issues/355#issuecomment-342665622>,
or mute
the thread

**Comment by shanshanpt** [comment]
@tgrabiec
Thanks :)
