### ISSUE TITLE
suggestion: python wrapper

### ISSUE THREAD

**Issue by jvanz** [scylladb/seastar#370]
One colleague of mine suggest create a python wrapper to the Seastar framework. I don't know if this is in the roadmap, but I think is a good idea.

**Comment by avikivity** [comment]
The Global Interpreter Lock and general Python slowness will kill any performance seastar can provide.

**Comment by yihuang** [comment]
We can embed sperate python interpreter inside seastar shards, I think that's an interesting thing to try.

**Comment by stepansojka** [comment]
@yihuang  I did a similar experiment with JavaScript/ChakraCore. It exposes seastar's http server to JavaScript and runs a separate JS runtime on every shard so that you can write JavaScript code like this:

```
server = new http.Server();

server.on('GET', '/hello', (req, resp) => {
    resp.status = 200;
    resp.body = "hello js";
});

server.listen(10000).then(
    () => console.log('listening on core', core.number())
);
```

(https://github.com/stepansojka/orthocanna-js/blob/master/examples/http.js)

According to my quick and very unscientific benchmark, this runs somewhat faster than NodeJS (both running on eight cores, the seastar thing without DPDK), but I think that's mainly because Chakra JIT-compiles the JavaScript to machine code, so it doesn't completely ruin the performance advantage that seastar gives you.

I guess that if you went with an interpreted language, it might completely erase the speedup that you get from seastar (see @avikivity 's answer above).

**Comment by avikivity** [comment]
Closing. If someone wants to contribute python or v8/nodejs integration, I'm certainly interested. I'm not sure if it should be part of Seastar or a layered project, but either way I'm happy to put it under the Seastar umbrella.
