### ISSUE TITLE
Should we make methods return future<T> as more as possible?

### ISSUE THREAD

**Issue by baiwfg2** [scylladb/seastar#410]
Hi. I wonder under what circumstances we should make a method return future<T>. Are there any good practices or general rules ?  On one hand, making a method return future<T> can help participate in future chain callback, so it's more like future-continuation paradigm, on the other hand the whole interface is full of futures, even the simplest one which just return a void type.

So I want to know in seastar world,  should we make methods return future<T> as more as possible, so that we got the following code style ?

```
future<T> A() {
	return B([] {
		return C([]{
		})
		...
	}
}
```

**Comment by nyh** [comment]
This does not report a bug or request a feature - it is more of an open-ended discussion. Please move it to the seastar-dev mailing list where I'll be happy to discuss it.
Please note that in many contexts, Seastar already converts immediately-returning functions into a function returning an immediately-available-future, using the seastar::futurize_apply() function mentioned in the tutorial. For example, you can do:
```c++
future<int> f() {
   seastar::sleep(1s).then([] { return 3; });
}
```
Even though the lambda function returns the integer 3, not a future<int>, the then() method, because it uses seastar::futurize_apply(), converts this lambda into one which returns an (immediately available) future, which then() expects to get.

**Comment by baiwfg2** [comment]
Sorry, I would have thought seastar-dev specifically discussion PATCH things and not found the seastar-user mailing list like scylla-user.  I'll post there.
