### ISSUE TITLE
http json string should be escaped before returning

### ISSUE THREAD

**Issue by amnonh** [scylladb/seastar#460]
The handler functions hide all the json related details.
Json string should be escaped for new line and special characters to be compliant.

[RFC 4627](http://www.ietf.org/rfc/rfc4627.txt)

**Comment by nyh** [comment]
@amnonh can you please explain what this issue is about? Which code needs to be fixed? I'm guessing some to_json() function somewhere is wrong? Can you please provide an example of what's wrong (a failing test would have been even better...)?

By the way, applications that don't leave the JSON encoding to Seastar are not vulnerable to this issue. For example, in Scylla Alternator we convert RapidJSON's value into a string ourselves, so it doesn't matter how Seastar does it. (To be honest, I'm not even sure why Seastar has specific JSON support. This is just one of hundred possible content types, I think we should have just let the application handle it - as Scylla Alternator does anyway, for example).

**Comment by amnonh** [comment]
It's referring to the API. the JSON support is because seastar has an API support.
And the API works with JSON.
The conversion from any type to json is done in json_return_type class.
Specifically for string, it should be escaped, so if a user would return a string like:
**Helo"world**
It would not break at the client

**Comment by nyh** [comment]
Ok, @jul-stas just encountered this bug in Scylla (https://github.com/scylladb/scylla/issues/9061) so I can now finally explain what this bug is about, and why it is indeed a serious bug.

In `src/json/formatter.cc` we have a bunch of `formatter::to_json()` overloads which are used by Seastar to convert a json_return_type (which HTTP handlers can return) containing Seastar's homebrewed JSON-like wrappers ("json_element", "json_list", etc.) into a string serialization of JSON.

The bug is that the string overload does the following trivial thing:
```c++
string formatter::to_json(const char* str) {
    sstring res = "\"";
    res += str;
    res += "\"";
    return res;
}
```

This is **wrong**. If the given str contains any special characters (quotes, backslashes, and a few other things), they must be escaped, or the returned string will not be valid JSON - and the client who receives the HTTP reply with this JSON will not be able to parse it. This is exactly what happened in Scylla in issue https://github.com/scylladb/scylla/issues/9061.

**Comment by nyh** [comment]
After finally understanding what this bug is about, I feel even more strongly about the comment I made a year and a half ago in one of my comments above:

> To be honest, I'm not even sure why Seastar has specific JSON support. This is just one of hundred possible content types, I think we should have just let the application handle it - as Scylla Alternator does anyway, for example).

I think it was a mistake to include very partial, and evidentially buggy, JSON support into Seastar. If we wanted Seastar to have official support for JSON it should have been more complete, better documented, and better tested.

**Comment by avikivity** [comment]
@nyh I agree it was a mistake, as Seastar itself doesn't need json. So it's acting like a utility library instead of focusing on its expertise.

We can consider deprecating it and asking users to move use their own json dependencies.
