### ISSUE TITLE
dns_test fails in C++14 mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#631]
After `./configure.py --c++-dialect c++14`:

```
[avi@avi seastar (master)]$ ./build/dev/tests/unit/dns_test 
Running 5 test cases...
unknown location(0): fatal error: in "test_bad_name_tcp": signal: SIGABRT (application abort requested)
../../src/testing/seastar_test.cc(37): last checkpoint
```

Works in C++17 mode.

**Comment by espindola** [comment]
I think I know what the issue is. At lest this is what it see with execution_stage_test:

alien uses boost::lockfree::queue, which requires allocating nodes that are 64 bytes aligned. The c++ allocator code has:

#if __cpp_aligned_new
use aligned new
#
use regular new

So in c++14 we get pointers that are not sufficiently aligned.

Maybe we should disable alien support when building with c++14?

**Comment by nyh** [comment]
According to `doc/compatibility.md` we only support C++20 and C++17, not C++14. @avikivity can we close this issue?

**Comment by avikivity** [comment]
Yes
