### ISSUE TITLE
Failure to initialize is not handled gracefully

### ISSUE THREAD

**Issue by kostja** [scylladb/seastar#640]
The bug can be reproduced by starting scylla without arguments.

I have an 4-core Intel(R) Core(TM) i7-8650U, 8 virtual cores. When I run scylla, it tries to start 8 shards by default. For some reason (I have not investigated what it is causing the resource shortage yet), the kernel fails to allocate 8 io queues on my system, which leads to a failure to initialize one of seastar reactors:
```
index 3ecf96e1..1a1db64a 100644
--- a/src/core/reactor.cc
+++ b/src/core/reactor.cc
@@ -1294,7 +1294,7 @@ reactor::reactor(unsigned id, reactor_backend_selector rbs, reactor_config cfg)
         _free_iocbs.push(&_iocb_pool[i]);
     }
     auto r = io_setup(max_aio, &_io_context);
-    assert(r >= 0);
+    throw_system_error_on(r == -1);
```
io_setup() failes with error code 11, resource temporarily unavailable. As can be seen from the source code, the error is not handled gracefully.
There is no exception handling for reactor/thread start failure in scylla either - but this would be a scylla bug. 
Finally, the reason I think it's a seastar bug, seastar can not shutdown gracefully on reactor creation failure: it tries to destroy a condition variable which is used to wait until all reactors have started, and fails:
```
Could not initialize seastar: std::system_error (error system:11, : Resource temporarily unavailable)
scylla: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:85: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
```

Please feel free to close if it is never supposed to work, I think it will be rather difficult to properly fix this bug. The workaround is to submit a smaller smp count explicitly as a startup option. Reporting this since I believe it is important to note that clean shutdown of seastar does not work, so it would be best to simply avoid it, by adding a function which would exit without calling any destructors. The alternative is, if we decide to make it work, covering all resource allocation paths with error injections and adding tests to the test suite.

**Comment by nyh** [comment]
I think that this *is* a Seastar bug, or rather a series of bugs :-) Indeed, throwing instead of asserting would be better, and making sure this exception actually works correctly (this condition variable thing) needs to be solved, and it would be great if you could submit patches.
But more fundamentally, if on a real machine (like yours), io_setup() fails, we need to understand why. The manual page says:
```
       EAGAIN The  specified  nr_events  exceeds the user's limit of available
              events, as defined in /proc/sys/fs/aio-max-nr.
```
On my machine 
```
$ cat /proc/sys/fs/aio-max-nr        
1048576
```
is it much lower on your machine? What is max_aio we try to pass? Who determines it? Could Seastar automatically lower max_aio when needed and what's the downside of doing this? (CC: @glommer ). If Seastar could recover by lowering max_aio, it should (perhaps with a warning that the user should increase /proc/sys/fs/aio-max-nr) - this will also avoid all the exception bugs you mentioned :-) But if we can't recover, Seastar should at least print an understandable error message perhaps mentioning /proc/sys/fs/aio-max-nr.

**Comment by denesb** [comment]
On my machine:
```
$ cat /proc/sys/fs/aio-max-nr  
65536
```
This practically means that I cannot run more than one seastar process parallely, meaning I have to run my (Scylla) tests single file, which takes ages.

**Comment by kostja** [comment]
Re submitting patches: I know from experience that it would be rather difficult to fix and maintain a correct fix. It may end up that fixing one or two destruction order failures is a low hanging fruit, but keeping destruction order correct in a complex library is an ongoing work. It is a technical debt which I personally abandoned at trying to fix previously in my career. The benefit is simply not worth it. So I would move towards not destroying any library state at exit, this would make for a faster exit, too.

**Comment by nyh** [comment]
@glommer considering that some users have aio-max-nr=65536, what do you think should Seastar do? Should it play along and try using a lower aio_max than it intended (perhaps with a warning), or refuse to run and direct the user to increase his aio-max-nr?

**Comment by glommer** [comment]
`[PATCH v3] improve error message on AIO setup failure` is on the mailing list for a while, but never got merged =(

**Comment by kostja** [comment]
``` %  cat /proc/sys/fs/aio-max-nr   
65536
```
Each reactor passed 10000 events by default. I have 8 core. Plus there are other io_setup calls during initialization, some pass 1024 events, some 2, some 1.
So the cause of the problem is lack of events indeed.
Increasing the constant is a valid workaround.

**Comment by nyh** [comment]
Should be fixed by commit 8c6cf573e51fa1920c6d6cc8969e317fe07d2b10 by @glommer. The Seastar application should now exit on startup (without a coredump) with the message:

> Could not setup Async I/O: {}. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application

I think this is enough to close the issue, although we can perhaps consider even better solutions in the future, including using whatever limit we are given instead of complaining that it is too low. Please reopen the issue if this patch didn't fix your problem, or open a new issue if you think we need a different solution.

**Comment by avikivity** [comment]
Reopened since scylla users are encountering it.

Possible fix:
 - calculate needed aio resources on startup
 - calculate available resource from fs.aio-max-nr - fs.aio-nr
 - hope there is no race
 - use aio backend if sufficient resources are availble, otherwise fall back on epoll

Another possible fix:
 - try to construct the aio backend, on failure construct the epoll backend

This is race-free, but on the other hand can end up with different reactors using different backends. It should work, but is strange.

**Comment by vladzcloudius** [comment]
@avikivity @xemul I see that we have the `reactor::max_aio` hardcoded to 1024.
Isn't it too low? Doesn't it define the maximum I/O concurrency per shard?
