### ISSUE TITLE
Is there a plan for RDMA support？Thanks.

### ISSUE THREAD

**Issue by junxfl** [scylladb/seastar#755]

**Comment by nyh** [comment]
There was some discussion about this in the seastar-dev mailing list recently - see https://groups.google.com/d/msg/seastar-dev/7om-JVblbJ4/pTTPpngKCwAJ - where @avikivity gave some ideas for whoever may think of implementing it. There were a couple of people on this thread who seemed interested in implementing it. The best place to inquire about this would be on the mailing list.

I'm closing this issue because it is not written as a feature request, but as a question. Feel free to open a new issue asking for the feature, instead of _about_ it. But if you do that, please do explain in more details exactly what you'd like this feature to be about. Is it about TCP/IP over RDMA? Or providing RDMA APIs? Or anything else?
