### ISSUE TITLE
IO cancellation

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#811]
The `write/read_file_dma` calls queue the request and do not resolve the returned future until the request goes throught the real IO. Callers want to cancnel the IO on timeout (scylladb/scylla#7340)

**Comment by vladzcloudius** [comment]
A small correction: callers want to be able to cancel I/O requests (not only due to timeout).
I think the RAI-like proposal from Avi on scylladb/scylla#7340 where I/O is tied to the originating context (e.g. query context) and cancelable by that context makes a lot of sense and is a way to go.
We should not bind this feature to timeout which is just one of the reasons why we'd want to cancel previously scheduled I/O requests.

**Comment by eliransin** [comment]
@xemul any news on that? Did you by any chance started working on that or is it somewhere down your queue? :slightly_smiling_face:

**Comment by xemul** [comment]
@eliransin , I made an attempt to implement this with small intrusiveness, but it didn't work, so we need to go some longer route. I'll continue, but right now it's not the highest priority in my queue.

**Comment by xemul** [comment]
I guess this issue can be closed already? @bhalevy

**Comment by eliransin** [comment]
Yes, @xemul  - thanks :slightly_smiling_face:
