### ISSUE TITLE
How to debug a Seastar program on VS2019 or VSCode? Segment fault is meeted.

### ISSUE THREAD

**Issue by ParanoidRoot** [scylladb/seastar#815]
i have already successfully builded and installed seastar on a Ubuntu (18.04 LTS) machine, and the seastar-branch is 19.06.
i have also successfully run the `get-started.cc` on this Ubuntu machine, which is compiled and build by CMake.
i am trying to debug the `get-started.cc` on my PC(win 10), and using the VS2019 as my IDE.
i created a CMake Project on VS2019 and successfully run the helloworld codes on Linux.
![image](https://user-images.githubusercontent.com/48121399/96117435-acf26600-0f1c-11eb-9156-ed3f4bc30dd5.png)
When i tried to add more codes about seastar, the segment fault is caused.
![image](https://user-images.githubusercontent.com/48121399/96117637-fc389680-0f1c-11eb-837f-d6a1222ca754.png)
How to fix this? Or how can i debug my seastar program on a windows PC?

**Comment by denesb** [comment]
Please ask questions on the [seastar-dev](mailto:seastar-dev@googlegroups.com) mailing list. But since I'm here... you can use `gdb` to debug your seastar application. But for finding segmantation fault using ASAN is much more convenient. Just build and run a debug build and ASAN should be used turned on automatically.
