### ISSUE TITLE
Seastar needs 10000 AIO slots for reactor_backend_aio::_polling_io

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#858]
Need to find out why this number is that big and if it can be reduced or made dynamic (scylladb/scylla-pkg#1867)

**Comment by xemul** [comment]
@avikivity , do you remember anything about this? It was introduced by 7398e901f 3 yrs ago without explanation on the 10k value and didn't change since then.

**Comment by avikivity** [comment]
See http://www.kegel.com/c10k.html. It's to support 10,000 connections per shard.

The best fix would be to move to io_uring, which needs pinned memory per shard, not pinned memory per connection. Of course that need kernel 5.4 or thereabouts, so it will take a few years for it to be widely available.

**Comment by nyh** [comment]
In May 2019 Glauber first noticed not being able to allocate the AIO buffer, and added the error message which you now noticed in https://github.com/scylladb/scylla-pkg/issues/1867 (Glauber's patch titled "improve error message on AIO setup failure").

In my review of Galuber's patch I noted that there is nothing holy about the number "10,000", and it would have been better if Seastar could reduce its demands depending on the available `aio-max-nr`, even if the specific number 10,000 cannot be achieved. Yes, this can mean that Seastar's concurrency will be limited, but we can warn about it - it doesn't need to be a reason not to start up at all, because many applications don't need this specific concurrency of 10,000. Also, theoretically, some applications may need more than 10,000, so this number should configurable, no?

**Comment by avikivity** [comment]
It's only possible to rely on aio-max-nr if there is only one application using aio on the system. That works for production deployments, but not tests that run in parallel.

**Comment by nyh** [comment]
> It's only possible to rely on aio-max-nr if there is only one application using aio on the system. That works for production deployments, but not tests that run in parallel.

I didn't really want us to rely on knowing aio-max-nr, we can try large allocations and fall back to smaller allocations if the larger ones failed. Of course for this Seastar needs to centralize its aio allocations so they can all scale down together instead of competing. And, yes, if multiple applications compete for this allocation there's nothing Seastar can do to prevent the other application taking the entire `aio-max-nr`. But the same is true for CPUs and memory, which Seastar tries to hog and will not cooperate well with another application which tries to hog the same resources.

For tests that run in parallel, just like we probably pass "-m" and "-c" options to the test application - avoid hogging all the memory and CPUs - we should also pass an option to allocate a much smaller number of aio items. There is no reason why tests should need max_pols=10,000 to run.

**Comment by avikivity** [comment]
It sounds reasonable to pass an option for tests. Also to fall back to smaller allocations, though that's quite hard - io_setup needs to run on the correct shard for NUMA friendliness, so we'll need to coordinate the retries.

**Comment by kostja** [comment]
Ubuntu 20 LTS here is already using 5.8 kernel. Fedora 33 is using 5.8 as well. RHEL will obviously lag behind, but looks like things are moving faster with modern kernel adoption than they used to.

**Comment by avikivity** [comment]
The problem is RHEL 8 with its 4.18 kernel. But they may backport it.

**Comment by avikivity** [comment]
> @avikivity , do you remember anything about this? It was introduced by [7398e90](https://github.com/scylladb/seastar/commit/7398e901f939bef714d96d1a57d7a9fc69b1b8be) 3 yrs ago without explanation on the 10k value and didn't change since then.

Probably from http://www.kegel.com/c10k.html

**Comment by avikivity** [comment]
Ah, I even wrote about it earlier.
