### ISSUE TITLE
I think the definition of future_base::do_wait() should be ...

### ISSUE THREAD

**Issue by chinese20201103** [scylladb/seastar#897]
void internal::future_base::do_wait() noexcept {
    //auto thread = thread_impl::get();
    //assert(thread);
    //thread_wake_task wake_task{thread};
    //wake_task.make_backtrace(); //wqf SEASTAR_TASK_BACKTRACE
    //_promise->_task = &wake_task;
    //thread_impl::switch_out(thread); //wqf Had thread_impl::switch_in been called?
	while (!_promise->_state->available())
		;
}

**Comment by tgrabiec** [comment]
Why do you think so?

This would make the reactor execute this loop and it wouldn't have a chance to execute other tasks, which may need to execute to make _promise ready.

**Comment by nyh** [comment]
Closing this issue as invalid, feel free to reopen (or open a different issue) if you can better explain what you meant to suggest, or explain what real problem you saw in your code that led you to make this specific suggestion.

As @tgrabiec said, this current implementation is deliberate, and necessary. The whole point of `future::get()` is to _context switch_ to running different tasks while the future that this task needs isn't ready yet. A tight loop like you suggested will never ever allow a context switch (Seastar has _non-preemptive_ multitasking). Moreover, as @tgrabiec said, it will very likely loop forever, because Seastar programs are sharded (each CPU core works on a different data set) so the future we are waiting for is actually waiting for something else that needs to happen on *this* core, and it can't happen as long as this task is doing an endless loop and not let other things run).

**Comment by chinese20201103** [comment]
https://github.com/scylladb/scylla/issues/7746
https://github.com/scylladb/scylla/issues/8451
I trace scylladb code with gdb for and find hanging at thread_impl::switch_out(thread). I will research ...
