### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by unicomp21** [scylladb/seastar#913]
If there was a PR for websocket support, would it be accepted?  The reason I ask, seastar looks like a great option for tunneling udp packets for gaming scenarios.  Might be useful for novel video conferencing approaches too.

https://github.com/ImmortalEmperor/UnrealEngine/issues/10

**Comment by nyh** [comment]
Hi, this is a bug tracker, for general discussions please use the mailing list (seastar-dev on googlegroups.com). I'll answer here but if you want to continue the discussion, let's do it on the mailing list.

Seastar is meant to be a low-level, reusable, library on many different applications will want to use. Not every coceivable feature written **with** Seastar needs to be **inside** Seastar. The (vague, I admit) criterion for something to enter Seastar itself is that the code is high quality and that we think that it might be useful for many applications. For example, we thought that many applications will want a simple HTTP server (e.g., to provide a REST API), which is why we put the HTTP server code in Seastar. There is definitely room to discuss whether or not websocket might be generally useful to many applications.

In any case, it makes a lot of sense for you to start developping your code outside Seastar, **using** Seastar - and only later when you have a working and presentable feature, decide whether you want it to live inside Seastar, or outside, as a separate open-source library using Seastar.
