### ISSUE TITLE
aio_general_context::queue may overflow the queue

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#920]
As of ed7dd4e016492eabb1123194b67a66234dfce077, aio_general_context::queue doesn't check there's enough room to queue a new iocb.

**Comment by raphaelsc** [comment]
@bhalevy https://github.com/scylladb/seastar/commit/ed7dd4e016492eabb1123194b67a66234dfce077 is this really the commit that introduced the regression? doesn't seem related.

**Comment by bhalevy** [comment]
> @bhalevy [ed7dd4e](https://github.com/scylladb/seastar/commit/ed7dd4e016492eabb1123194b67a66234dfce077) is this really the commit that introduced the regression? doesn't seem related.

no, it's just a point in time of the current HEAD is am working against.

**Comment by travisdowns** [comment]
For the record, despite this `last < end` assert in https://github.com/scylladb/seastar/commit/a58d2790199216e6cdc14aba2055ef3296be4fa4 being "extremely unlikely to fail in practice", we do see it fail in practice with the default max_polls of 10,000, when many clients are connected.

It is not actually clear if 10,001 polls actually occur in task quota period (0.5 ms) or if some reason the task quota period is exceeded allowing 10,001 polls to fit in. It seems _plausible_ that 10,001 poll occur quickly since e.g., a call like `pollable_fd::readable()` is a fairly fast operation entirely in userspace.
