### ISSUE TITLE
SIG35 with seastar::parallel_for_each

### ISSUE THREAD

**Issue by gamedev8** [scylladb/seastar#985]
Is there a way to get the following code to execute without throwing a SIG35? Let's assume you don't have access to the `slow()` function, or it's not easy to change.
If you change `parallel_for_each` to `do_for_each` then it executes. 

```
#include <seastar/core/app-template.hh>
#include <seastar/core/reactor.hh>
#include <vector>
#include <iostream>

namespace ss = seastar;

void slow() {
    size_t foo = 0;
    for (int a = 0; a < 100000000; ++a) {
        foo += 1;
    }
}

ss::future<> go() {
    std::vector<int> ints {1,2,3,4};

    return ss::parallel_for_each(ints, [&](auto const& i) {
        return ss::futurize_invoke(slow).then([] {
            std::cout << "Done\n" << std::flush;
        });
    });
}

int main(int argc, char** argv) {
    ss::app_template app;
    app.run(argc, argv, go);
}
```

I've create a repo with this code here
https://github.com/vibelife/seastar-sig35

Some other info:
```
$ git branch
* seastar-20.05-branch
```
```
$ sudo lshw -C cpu
  *-cpu                     
       description: CPU
       product: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
       vendor: Intel Corp.
```
```
$ gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
```

**Comment by nyh** [comment]
This is not a bug, it's working as designed, and the right place to discuss this would be the Seastar mailing list. But since you asked here, I'll try to answer:

Seastar uses "SIG35" (that's SIGRTMIN+1) in its "stall detector". Seastar has _cooperative_ multitasking: Continuations are expected to finish quickly on their own and schedule their own continuations if they want to do more work. If one continuation goes into a busy loop for a full second - as in your example - this will ruin any chance of achieving good latency (any request would be delayed by a full second after this hog-of-a-continuation!) so is highly undesirable in a Seastar application.

You may wonder why Seastar doesn't have **preemptive** multi-tasking like threads on OSs. Well, this is by design. Preemptive multi-tasking is slower, and makes programming difficult because you need to start using locks (or preemption-disable, or similar mechanisms) in many places just because you're not sure where your code might be preempted.

Anyway, a "proper" Seastar application would not use a huge "for" loop like this. Instead, continuation-based code can use one of the loop idioms in <seastar/core/loop.hh> - which ensure that the loop is preempted every once in a while (I think the default today is half a millisecond?), and coroutine-based code can use a normal loop with `co_await coroutine::maybe_yield();` (this maybe_yield yields after the same half a millisecond), or use `need_preempt()` or similar techniques (which should, undoubtedly, be documented in tutorial.md but aren't).

**Comment by gamedev8** [comment]
Ok thanks for the explanation.
